---

- name: Adding group {{ username }}
  group:
    name={{ username }}
    state: present

- name: Adding user {{ username }}
  user: name={{ username }}
        group={{ username }}
        shell=/bin/bash
        password= {{ username }}
        groups=sudo
        append=yes
