---
# roles: user, oracle-jdk8, tomcat8, apache2

- hosts: foo
  remote_user: "{{ username }}"
  become: true
  vars_files:
    - vars/install

  roles:
    - { role: user, tags: ['user'] }
    - { role: oracle-jdk8, tags: ['oracle-jdk8'] }
    - { role: apache2, tags: ['apache2'] }
    - { role: tomcat8, tags: ['tomcat8'] }
