---
- hosts: install
  remote_user: "{{ username }}"
  become: false
  vars_files:
    - vars/install
    - vars/deploy

  roles:
  - { role: deploy/tomcat-start, tags: ['tomcat-start'] }
  - { role: deploy/common-apache-start, tags: ['apache-start'] }
