---
- hosts: install
  remote_user: "{{ username }}"
  become: false
  vars_files:
    - vars/install
    - vars/deploy

  roles:
  - { role: deploy/tomcat-stop, tags: ['tomcat-stop'] }
  - { role: deploy/common-apache-stop, tags: ['apache-stop'] }
